<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Gift Wrap for Magento 2
 */
?>
<div class="amwrap-popup-title">
    <p class="amwrap-title"><?= $block->escapeHtml(__('Wrap All Available Items')) ?></p>
    <p class="amwrap-description">
        <?= $block->escapeHtml(__('Item(s) will be sent packaged in a gift box.
         Please remember, once enclosed you will be unable to see the contents of the package. ')) ?>
    </p>
</div>
