<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_GiftWrap
 */
?>
<?php

use Amasty\GiftWrap\Api\SaleData\WrapInterface;

/** @var \Amasty\GiftWrap\Block\Checkout\Cart\Wrap\ListWrap $block */
?>

<div class="checkoutWrapCardInfo checkout-gift-wrapper" id="checkoutWrapCardInfo">
    <div class="step-title">Gift Wrap &amp; Card Option</div>
    
</div>