<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Gift Wrap for Magento 2
 */
    /** @var \Amasty\GiftWrap\Block\Product\View\Card $block */
    /** @var \Amasty\GiftWrap\Model\MessageCard\MessageCard $card */
    /** @var \Amasty\GiftWrap\Model\SaleData\AbstractWrap|null $selectedWrap */

    $selectedWrap = $block->getSelectedWrap();
?>

<?php if ($block->getMessageCards()): ?>
<h3 class="amwrap-card-title"><?= $block->escapeHtml(__("Want to Add Gift Message Card? (optional)")); ?></h3>
<ul class="amwrap-slider-block"
    data-amwrap-js="slide-list"
    data-mage-init='{"amwrapSlick": {}}'>
    <?php foreach ($block->getMessageCards() as $card): ?>
        <?php $currentSelected = $selectedWrap && $selectedWrap->getAmGiftWrapCardId() == $card->getEntityId() ?>
        <li class="amwrap-slide <?= $currentSelected ? '-active' : '' ?>"
            data-amcard-id="<?= (int)$card->getEntityId(); ?>"
            data-amwrap-js="item">
            <?php if ($src = $block->getImageSrc($card->getImage())): ?>
                <img class="amwrap-img"
                     alt="<?= $block->escapeHtml($card->getName()); ?>"
                     src="<?= $block->escapeUrl($src); ?>"
                     data-amwrap-js="img"
                />
            <?php endif; ?>
            <p class="amwrap-name" data-amwrap-js="name"><?= $block->escapeHtml($card->getName()); ?></p>
            <p class="amwrap-price" data-amwrap-js="price"><?= $block->getPriceHtml($card); ?></p>
            <input class="amwrap-check" data-amwrap-js="checkbox" type="radio" name="amwrap[card_id]" value="<?= (int)$card->getEntityId(); ?>" <?= $currentSelected ? 'checked' : '' ?>/>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<div class="amwrap-textarea-block <?= /** @noEscape */ $block->getIsAllowedMessageWithoutCard() ? '-hidden' : ''; ?>"
     data-amwrap-js="message-wrap">
    <label class="amwrap-label">
        <?= $block->escapeHtml(__('Add Gift Message')) ?>
    </label>
    <textarea class="amwrap-textarea"
              name="amwrap[gift_message]"
              title="<?= $block->escapeHtml(__('Add Gift Message')); ?>"
              rows="2"
              data-amwrap-js="card-message"
              placeholder="<?= $block->escapeHtml($block->getMessagePlaceholder()); ?>"><?= $block->escapeHtml($selectedWrap && $selectedWrap->getAmGiftWrapGiftMessage() ? $selectedWrap->getAmGiftWrapGiftMessage() : '') ?></textarea>

</div>

<?= $block->getLayout()->getBlock('amgiftwrap.prices.checkbox')->toHtml(); ?>
