<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Gift Wrap for Magento 2
 */
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<!-- <p class="amwrap-finish-message">
    <span class="amwrap-message">
        <?= $block->escapeHtml(__('Please check and confirm the chosen wrapping')); ?>
    </span>
</p> -->

<ul class="amwrap-choose-list" data-amwrap-js="choose-list"></ul>
